#!/bin/bash
# This script builds and deploys the Astro site to Cloudflare Pages

# Exit on any error
set -e

echo "Building Astro site..."
npm run build

echo "Site built successfully!"

echo "To deploy to Cloudflare Pages:"
echo "1. Go to https://dash.cloudflare.com/"
echo "2. Navigate to Workers & Pages > Create > Pages > Upload Assets"
echo "3. Select the 'dist' folder generated by the build process"
echo "4. Set the following build settings:"
echo "   - Build command: npm run build"
echo "   - Build output directory: dist"